kind: pipeline
name: default

steps:
- name: test
  image: golang:1.12
  commands:
  - cd xorm
  - go build -v -mod=vendor
  - go test -v -mod=vendor -race -coverprofile=coverage.txt -covermode=atomic